notifications:
  email: false

language: generic

sudo: required

services:
  - docker

env: ROOTFS="$TRAVIS_BUILD_DIR/product/rootfs.tar.xz"

script:
  - ./nano build image
  - ./nano build rootfs
  - ./nano pull rootfs

  # Test rootfs readable.
  - '[[ -r $ROOTFS ]]'

  # Test rootfs begins with root entry.
  - '[[ $(tar tf "$ROOTFS" | head -1) = ./ ]]'

  # Test rootfs includes overlay entries.
  - tar tf "$ROOTFS" | grep -Fx ./srv/

  # Test rootfs excludes post_build entries.
  - '! tar tf "$ROOTFS" | grep -Fx ./home/ftp/'
